### ISSUE TITLE
Illegal attempt to associate a collection with two open sessions

### ISSUE THREAD

**Issue by pedr0-fr** [sveryovka/easy-criteria#13]
Was getting the exception in the title... After I rewrote my query using JPA criteria instead of easy criteria, it worked...

**Comment by s4gh** [comment]
Hi. Can you please provide some query sample or any other additional details? What object model you had and what query you was trying to execute?

**Comment by pedr0-fr** [comment]
There are four entities with a lot of many to many and one to many relationships, hard to reproduce, Will get in touch in case I can make a minimum reproducible code but for now just want to put it out there.

**Comment by pedr0-fr** [comment]
I'm closing this because I might have made a mistake on how I created my entity manager. It might have been my fault.
