### ISSUE TITLE
Using annotations from Validation result in classes that don't compile

### ISSUE THREAD

**Issue by gunnar-g** [sveryovka/easy-criteria#9]
I have an entity that uses javax.validation.constraints.Size. The resulting class contains this
`    public StringPropertyAttribute<UserEntity, (@javax.validation.constraints.Size(min=8, message="Minimum password length: 8 characters") :: java.lang.String)> password = new StringPropertyAttribute<>("password", this, (@javax.validation.constraints.Size(min=8, message="Minimum password length: 8 characters") :: java.lang.String).class);
` and gives following compilation issue
`..../user/model/QUserEntity_.java:14: error: ';' expected
    public StringPropertyAttribute<UserEntity, (@javax.validation.constraints.Size(min=8, message="Minimum password length: 8 characters") :: java.lang.String)> password = new StringPropertyAttribute<>("password", this, (@javax.validation.constraints.Size(min=8, message="Minimum password length: 8 characters") :: java.lang.String).class);`

**Comment by gunnar-g** [comment]
[anotationPatch.txt](https://github.com/sveryovka/easy-criteria/files/2568485/anotationPatch.txt)
This should fix it

**Comment by gunnar-g** [comment]
@sveryovka apparently this is fixed with the other pull request?

**Comment by s4gh** [comment]
For some reason suggested patch has not worked. I have added other changes in https://github.com/sveryovka/easy-criteria/pull/12
